apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dlppolicies.audimodal.ai
  labels:
    app: audimodal
    component: crd
spec:
  group: audimodal.ai
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - name
            - rules
            properties:
              name:
                type: string
                description: "Policy name"
                minLength: 1
                maxLength: 100
              description:
                type: string
                description: "Policy description"
                maxLength: 500
              enabled:
                type: boolean
                description: "Whether the policy is enabled"
                default: true
              priority:
                type: integer
                description: "Policy priority (higher number = higher priority)"
                minimum: 1
                maximum: 1000
                default: 100
              scope:
                type: object
                description: "Policy scope and targeting"
                properties:
                  tenants:
                    type: array
                    description: "Tenant IDs this policy applies to (empty = all tenants)"
                    items:
                      type: string
                  dataSources:
                    type: array
                    description: "Data source names this policy applies to (empty = all sources)"
                    items:
                      type: string
                  fileTypes:
                    type: array
                    description: "File types this policy applies to (empty = all types)"
                    items:
                      type: string
                    default: ["*"]
                  tags:
                    type: object
                    description: "Key-value tags for targeting"
                    additionalProperties:
                      type: string
              rules:
                type: array
                description: "DLP rules in this policy"
                minItems: 1
                items:
                  type: object
                  required:
                  - name
                  - type
                  - action
                  properties:
                    name:
                      type: string
                      description: "Rule name"
                      minLength: 1
                      maxLength: 100
                    description:
                      type: string
                      description: "Rule description"
                      maxLength: 500
                    type:
                      type: string
                      description: "Rule type"
                      enum:
                      - "regex_pattern"
                      - "keyword_list"
                      - "ml_classifier"
                      - "data_type_detector"
                      - "compliance_checker"
                      - "custom_function"
                    severity:
                      type: string
                      description: "Rule severity level"
                      enum: ["low", "medium", "high", "critical"]
                      default: "medium"
                    action:
                      type: string
                      description: "Action to take when rule matches"
                      enum: ["block", "redact", "mask", "encrypt", "alert", "quarantine", "allow_with_approval"]
                    config:
                      type: object
                      description: "Rule-specific configuration"
                      properties:
                        # Regex pattern configuration
                        pattern:
                          type: string
                          description: "Regular expression pattern"
                        flags:
                          type: string
                          description: "Regex flags (i, m, s, etc.)"
                        confidenceThreshold:
                          type: number
                          description: "Confidence threshold (0.0-1.0)"
                          minimum: 0.0
                          maximum: 1.0
                          default: 0.8
                        # Keyword list configuration
                        keywords:
                          type: array
                          description: "List of keywords to match"
                          items:
                            type: string
                        caseSensitive:
                          type: boolean
                          description: "Whether keyword matching is case sensitive"
                          default: false
                        wholeWordsOnly:
                          type: boolean
                          description: "Whether to match whole words only"
                          default: true
                        # ML classifier configuration
                        model:
                          type: string
                          description: "ML model identifier"
                        modelVersion:
                          type: string
                          description: "ML model version"
                        # Data type detector configuration
                        dataTypes:
                          type: array
                          description: "Data types to detect"
                          items:
                            type: string
                            enum:
                            - "ssn"
                            - "credit_card"
                            - "email"
                            - "phone_number"
                            - "ip_address"
                            - "passport_number"
                            - "driver_license"
                            - "bank_account"
                            - "medical_record"
                            - "tax_id"
                            - "custom"
                        # Compliance checker configuration
                        regulations:
                          type: array
                          description: "Regulatory compliance frameworks"
                          items:
                            type: string
                            enum:
                            - "gdpr"
                            - "hipaa"
                            - "pci_dss"
                            - "sox"
                            - "ccpa"
                            - "ferpa"
                            - "glba"
                            - "custom"
                        # Redaction/masking configuration
                        redactionStyle:
                          type: string
                          description: "How to redact/mask sensitive data"
                          enum: ["asterisk", "hash", "placeholder", "removal", "encryption"]
                          default: "asterisk"
                        preserveFormat:
                          type: boolean
                          description: "Whether to preserve original format when redacting"
                          default: true
                        # Custom function configuration
                        functionName:
                          type: string
                          description: "Name of custom function to execute"
                        functionParams:
                          type: object
                          description: "Parameters for custom function"
                          additionalProperties: true
                    exceptions:
                      type: array
                      description: "Exceptions to this rule"
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            enum: ["file_path", "content_type", "user_role", "time_window", "data_source"]
                          value:
                            type: string
                          operator:
                            type: string
                            enum: ["equals", "contains", "starts_with", "ends_with", "regex"]
                            default: "equals"
              actions:
                type: object
                description: "Policy-level action configuration"
                properties:
                  defaultAction:
                    type: string
                    description: "Default action when no specific rule action applies"
                    enum: ["allow", "block", "alert"]
                    default: "alert"
                  notifications:
                    type: object
                    properties:
                      channels:
                        type: array
                        description: "Notification channels"
                        items:
                          type: string
                          enum: ["email", "slack", "webhook", "syslog", "splunk"]
                      escalation:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          rules:
                            type: array
                            items:
                              type: object
                              properties:
                                after:
                                  type: string
                                  description: "Escalate after this duration"
                                to:
                                  type: array
                                  description: "Escalate to these channels"
                                  items:
                                    type: string
                  quarantine:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      location:
                        type: string
                        description: "Quarantine storage location"
                      retentionDays:
                        type: integer
                        description: "Quarantine retention period"
                        minimum: 1
                        maximum: 2555
                        default: 30
                  audit:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      logLevel:
                        type: string
                        enum: ["minimal", "standard", "detailed"]
                        default: "standard"
                      retentionDays:
                        type: integer
                        minimum: 30
                        maximum: 2555
                        default: 365
              schedule:
                type: object
                description: "Policy scheduling and lifecycle"
                properties:
                  effectiveDate:
                    type: string
                    format: date-time
                    description: "When policy becomes effective"
                  expirationDate:
                    type: string
                    format: date-time
                    description: "When policy expires"
                  activeHours:
                    type: object
                    properties:
                      timezone:
                        type: string
                        default: "UTC"
                      schedule:
                        type: string
                        description: "Cron schedule for when policy is active"
                        default: "* * * * *"
              compliance:
                type: object
                description: "Compliance and regulatory mapping"
                properties:
                  frameworks:
                    type: array
                    description: "Applicable compliance frameworks"
                    items:
                      type: string
                  controls:
                    type: array
                    description: "Specific control requirements"
                    items:
                      type: object
                      properties:
                        framework:
                          type: string
                        controlId:
                          type: string
                        description:
                          type: string
                  riskLevel:
                    type: string
                    enum: ["low", "medium", "high", "critical"]
                    default: "medium"
          status:
            type: object
            properties:
              phase:
                type: string
                description: "Current policy phase"
                enum: ["Pending", "Active", "Suspended", "Expired", "Failed"]
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["Ready", "Validated", "Deployed", "Active", "Effective"]
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              statistics:
                type: object
                properties:
                  totalScans:
                    type: integer
                    description: "Total number of scans performed"
                  totalMatches:
                    type: integer
                    description: "Total number of policy matches"
                  lastScan:
                    type: string
                    format: date-time
                    description: "Last scan timestamp"
                  ruleStatistics:
                    type: array
                    description: "Per-rule statistics"
                    items:
                      type: object
                      properties:
                        ruleName:
                          type: string
                        matches:
                          type: integer
                        lastMatch:
                          type: string
                          format: date-time
                        falsePositives:
                          type: integer
                        accuracy:
                          type: number
                          format: float
              deploymentStatus:
                type: object
                properties:
                  deployed:
                    type: boolean
                    description: "Whether policy is deployed to engines"
                  deployedAt:
                    type: string
                    format: date-time
                  deployedVersion:
                    type: string
                  engines:
                    type: array
                    description: "DLP engines where policy is deployed"
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        status:
                          type: string
                          enum: ["deployed", "failed", "pending"]
                        version:
                          type: string
                        lastUpdate:
                          type: string
                          format: date-time
              violations:
                type: object
                properties:
                  recentViolations:
                    type: array
                    description: "Recent policy violations (last 24h)"
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                        severity:
                          type: string
                        ruleName:
                          type: string
                        source:
                          type: string
                        action:
                          type: string
                        details:
                          type: string
              observedGeneration:
                type: integer
                description: "Generation of the spec that was last processed"
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: Policy phase
      jsonPath: .status.phase
    - name: Rules
      type: integer
      description: Number of rules
      jsonPath: .spec.rules.length
    - name: Priority
      type: integer
      description: Policy priority
      jsonPath: .spec.priority
    - name: Violations
      type: integer
      description: Recent violations
      jsonPath: .status.violations.recentViolations.length
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: dlppolicies
    singular: dlppolicy
    kind: DLPPolicy
    shortNames:
    - dlp
    - policy
    categories:
    - audimodal
    - security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: audimodal-dlp-manager
  labels:
    app: audimodal
    component: rbac
rules:
- apiGroups: ["audimodal.ai"]
  resources: ["dlppolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list", "watch", "update", "patch"]