# Audimodal.ai Server Configuration
# This is an example configuration file showing all available options
# Copy this file and customize it for your environment

# Server settings
host: "0.0.0.0"
port: 8080

# TLS/HTTPS settings
tls_enabled: false
tls_cert_file: ""
tls_key_file: ""

# Timeouts
read_timeout: "30s"
write_timeout: "30s"
idle_timeout: "120s"
shutdown_timeout: "30s"

# CORS settings
cors_enabled: true
cors_allowed_origins:
  - "*"
cors_allowed_methods:
  - "GET"
  - "POST"
  - "PUT"
  - "DELETE"
  - "OPTIONS"
cors_allowed_headers:
  - "*"

# Rate limiting
rate_limit_enabled: true
rate_limit_rps: 100
rate_limit_burst: 200

# Authentication
auth_enabled: true
jwt_secret: ""  # Set this to a secure random string
jwt_expiration: "24h"
api_key_header: "X-API-Key"

# Request logging
log_requests: true
log_request_body: false
log_response_body: false
log_headers: false
log_level: "info"
log_format: "json"  # json or text

# Health check
health_check_path: "/health"
health_check_timeout: "30s"

# Metrics
metrics_enabled: true
metrics_path: "/metrics"

# API settings
api_prefix: "/api/v1"
max_request_size: 10485760  # 10MB
request_id_header: "X-Request-ID"

# Pagination defaults
default_page_size: 20
max_page_size: 100

# Database configuration
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: ""
  database: "audimodal"
  ssl_mode: "disable"
  
  # Connection pool settings
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"
  conn_max_idle_time: "30m"
  
  # Performance settings
  log_level: "warn"
  slow_threshold: "200ms"
  
  # Migration settings
  auto_migrate: false

# DeepLake API configuration
deeplake_api:
  # API connection settings
  base_url: "http://localhost:8000"  # Use https:// in production
  api_key: "dev-key-12345"  # Set to actual API key in production
  tenant_id: ""  # Optional tenant ID for multi-tenancy
  timeout: "30s"
  retries: 3
  user_agent: "Audimodal.ai-Go/1.0"
  
  # Connection pool settings
  max_idle_conns: 10
  max_conns_per_host: 100
  idle_conn_timeout: "90s"
  
  # TLS settings for API client
  tls_insecure_skip_verify: false  # Never set to true in production
  tls_cert_file: ""  # Optional client certificate
  tls_key_file: ""   # Optional client private key
  tls_ca_file: ""    # Optional CA certificate for verification
  
  # Health check settings
  health_check_enabled: true
  health_check_interval: "30s"
  health_check_timeout: "10s"
  
  # Cache settings
  cache_enabled: true
  cache_ttl: "5m"
  cache_max_size: 1000
  
  # Rate limiting for API calls (optional)
  rate_limit_enabled: false
  rate_limit_rps: 100.0
  rate_limit_burst: 200