apiVersion: v1
kind: ConfigMap
metadata:
  name: eaiingest-config
  namespace: eaiingest
  labels:
    app.kubernetes.io/name: eaiingest
    app.kubernetes.io/component: config
data:
  app.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 120s
      max_header_bytes: 1048576
      
    logging:
      level: "info"
      format: "json"
      output: "stdout"
      
    metrics:
      enabled: true
      path: "/metrics"
      port: 9090
      
    tracing:
      enabled: true
      service_name: "eaiingest"
      sampler_type: "probabilistic"
      sampler_param: 0.1
      
    auth:
      jwt:
        issuer: "eaiingest"
        audience: "eaiingest-api"
        expiry: "24h"
        refresh_expiry: "168h"
      
    database:
      max_open_connections: 25
      max_idle_connections: 5
      connection_max_lifetime: "5m"
      connection_max_idle_time: "5m"
      
    redis:
      max_retries: 3
      retry_delay: "100ms"
      pool_size: 10
      pool_timeout: "4s"
      idle_timeout: "5m"
      
    storage:
      local:
        base_path: "/app/data/storage"
        max_file_size: "100MB"
      aws:
        region: "us-west-2"
        timeout: "30s"
      gcp:
        timeout: "30s"
      azure:
        timeout: "30s"
        
    processing:
      max_concurrent_jobs: 10
      job_timeout: "30m"
      retry_attempts: 3
      retry_delay: "5s"
      
    classification:
      max_concurrent_classifications: 10
      default_timeout: "30s"
      max_text_length: 1000000
      max_batch_size: 100
      
    dlp:
      enabled: true
      confidence_threshold: 0.8
      max_scan_size: "10MB"
      
    chunking:
      default_strategy: "fixed_size"
      max_chunk_size: 4096
      default_overlap: 200

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eaiingest-nginx-config
  namespace: eaiingest
  labels:
    app.kubernetes.io/name: eaiingest
    app.kubernetes.io/component: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
                        
        access_log /var/log/nginx/access.log main;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain application/json application/xml;
        
        upstream eaiingest_backend {
            least_conn;
            server eaiingest-service:8080 max_fails=3 fail_timeout=30s;
        }
        
        server {
            listen 80;
            server_name _;
            
            client_max_body_size 100M;
            client_body_timeout 60s;
            client_header_timeout 60s;
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            location / {
                proxy_pass http://eaiingest_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 30s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
                proxy_buffering on;
                proxy_buffer_size 4k;
                proxy_buffers 8 4k;
            }
        }
    }