apiVersion: v1
kind: Namespace
metadata:
  name: eaiingest
  labels:
    app.kubernetes.io/name: eaiingest
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubernetes
---
apiVersion: v1
kind: LimitRange
metadata:
  name: eaiingest-limits
  namespace: eaiingest
spec:
  limits:
  - type: Container
    default:
      memory: "1Gi"
      cpu: "1000m"
    defaultRequest:
      memory: "256Mi"
      cpu: "100m"
  - type: PersistentVolumeClaim
    max:
      storage: "100Gi"
    min:
      storage: "1Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: eaiingest-quota
  namespace: eaiingest
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"